name: Desktop | CI checks
on:
  push:
    paths-ignore:
      - "apps/landing"
      - "apps/mobile"
      - "apps/inbox"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        id: pnpm-install

      - name: Install dependencies
        run: pnpm -F desktop install

      - name: Lint
        run: pnpm -F desktop lint
